# Docker-compose.yml version support, not internal version of this composition.
version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: upkoding
      POSTGRES_DB: upkoding
      POSTGRES_PASSWORD: upkoding
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: dev
    environment:
      DATABASE_URL: postgres://upkoding:upkoding@db:5432/upkoding
      # DATABASE_URL: postgresql://upkoding_user:TIoNEvIGUNdOmuStanKStISTOC@upkoding-postgresql-sgp1-do-user-543596-0.b.db.ondigitalocean.com:25060/upkoding_db?sslmode=require
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  static:
    image: node:14-slim
    working_dir: /static
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./_static:/static
