name: On Main push and PR (Unit tests, runnable test & build :edge image)

on:
  push:
    branches: feat/codeblocks
  pull_request:
    branches: feat/codeblocks

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Compose test
        run: docker-compose run --rm web python manage.py test

      - name: Compose up
        run: docker-compose up --detach web

      - name: Check its running
        run: docker ps -a

      - name: Check logs
        run: docker-compose logs

      - name: Compose down
        run: docker-compose down

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        id: docker_build
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/upkoding:edge
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        if: github.event_name != 'pull_request'
        run: echo ${{ steps.docker_build.outputs.digest }}
