name: On PR run unit tests

on:
  push:
    branches:
      - feat/codeblocks

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compose test
        run: docker-compose run --rm web python manage.py test

      - name: Compose up
        run: docker-compose up --detach web

      - name: Check its running
        run: docker ps -a

      - name: Check logs
        run: docker-compose logs

      - name: Compose down
        run: docker-compose down
